FROM php:8.4-fpm-alpine

RUN apk add --no-cache \
    bash \
    git \
    curl \
    unzip \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    freetype-dev \
    libxml2-dev \
    oniguruma-dev \
    zip \
    icu-dev \
    mysql-client \
    supervisor

RUN docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
        --with-webp \
 && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        mbstring \
        exif \
        pcntl \
        bcmath \
        intl \
        gd \
        opcache

ENV TZ=America/Sao_Paulo

WORKDIR /var/www/html

COPY . .

# Configura socket no www.conf
RUN sed -i 's|^listen = .*|listen = /var/run/php-fpm-sockets/ollama-chat.sock|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^;listen.owner =.*|listen.owner = www-data|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^;listen.group =.*|listen.group = www-data|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^;listen.mode =.*|listen.mode = 0660|' /usr/local/etc/php-fpm.d/www.conf


# Instala dependências
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
 && composer install --no-dev --optimize-autoloader \
 && php artisan config:cache \
 && php artisan route:cache \
 && php artisan view:cache

# 🔧 Comando final que garante o uso da configuração correta
CMD ["php-fpm", "-F", "-y", "/usr/local/etc/php-fpm.conf"]
