FROM php:8.4-fpm-alpine

# Dependências essenciais
RUN apk add --no-cache \
    bash \
    git \
    curl \
    unzip \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    freetype-dev \
    libxml2-dev \
    oniguruma-dev \
    zip \
    icu-dev \
    mysql-client \
    supervisor

# Instala extensões PHP
RUN docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
        --with-webp \
 && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        mbstring \
        exif \
        pcntl \
        bcmath \
        intl \
        gd \
        opcache

# Configura timezone
ENV TZ=America/Sao_Paulo

WORKDIR /var/www/html

COPY . .

# Configura PHP-FPM para usar socket exclusivo
RUN sed -i 's|^listen = .*|listen = /var/run/php-fpm-sockets/ollama-chat.sock|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^;listen.owner =.*|listen.owner = www-data|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^;listen.group =.*|listen.group = www-data|' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's|^;listen.mode =.*|listen.mode = 0660|' /usr/local/etc/php-fpm.d/www.conf

# Instala Composer e dependências do Laravel
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
 && composer install --no-dev --optimize-autoloader \
 && php artisan config:cache \
 && php artisan route:cache \
 && php artisan view:cache

 RUN mkdir -p /var/run/php-fpm-sockets && \
    chown www-data:www-data /var/run/php-fpm-sockets && \
    chmod 775 /var/run/php-fpm-sockets

CMD ["php-fpm"]
